language: generic
sudo: required
services:
  - docker
before_install:
  - ./run-after-clone.sh
  - docker build -t make-test .
script:
  - docker run -e CI=true make-test
after_success:
  - echo "success"