# created by jakub
FROM ubuntu as builder
RUN apt-get update
RUN apt-get -y install g++ cmake libboost-test-dev protobuf-compiler libprotobuf-dev
WORKDIR /app
COPY . .
RUN cmake .
RUN make

FROM ubuntu
WORKDIR /app
RUN apt-get update && apt-get -y install protobuf-compiler  libprotobuf-dev
COPY --from=builder ./app/src/server/server .
CMD ./server