//created by Piotr
#ifndef P2P_NETWORK_TORRENT_H
#define P2P_NETWORK_TORRENT_H


#include <cstdio>
#include <cstdint>
#include <string>
#include <TcpMessage.pb.h>

class Torrent {
public:
	uint64_t hashed;		// hash generated by a tracker
	uint32_t size;			// 32 bits = ~4GB max file size
	std::string fileName;

	Torrent();
	Torrent(uint32_t size, std::string fileName);
	Torrent(uint64_t hashed, uint32_t size, std::string fileName);
	explicit Torrent(const TorrentMessage &msg);
	TorrentMessage* toMsg();

	void genDefaultHash();
	void genSaltedHash(uint32_t salt);
};


#endif //P2P_NETWORK_TORRENT_H
